In [1]:
import cv2
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
import pygame
from pygame import mixer
from twilio.rest import Client


pygame 2.1.2 (SDL 2.0.18, Python 3.9.7)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')
model = load_model(r'C:\Users\Varun Bharadwaj\Desktop\Final\Models\model.h5')

In [3]:
mixer.init()
sound= mixer.Sound(r'C:\Users\Varun Bharadwaj\Desktop\Final\alert\alarm.wav')
cap = cv2.VideoCapture(0)
Score = 0
while True:
    ret, frame = cap.read()
    height,width = frame.shape[0:2]
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces= face_cascade.detectMultiScale(gray, scaleFactor= 1.2, minNeighbors=3)
    eyes= eye_cascade.detectMultiScale(gray, scaleFactor= 1.1, minNeighbors=1)
    
    cv2.rectangle(frame, (0,height-50),(200,height),(0,0,0),thickness=cv2.FILLED)
    
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,pt1=(x,y),pt2=(x+w,y+h), color= (255,0,0), thickness=3 )
        
    for (ex,ey,ew,eh) in eyes:
        #cv2.rectangle(frame,pt1=(ex,ey),pt2=(ex+ew,ey+eh), color= (255,0,0), thickness=3 )
        
        # preprocessing steps
        eye= frame[ey:ey+eh,ex:ex+ew]
        eye= cv2.resize(eye,(80,80))
        eye= eye/255
        eye= eye.reshape(80,80,3)
        eye= np.expand_dims(eye,axis=0)
        # preprocessing is done now model prediction
        prediction = model.predict(eye)
        print(prediction)
        
        # if eyes are closed
        if prediction[0][0]>0.30:
            cv2.putText(frame,'closed',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score=Score+1
            if(Score>20):
                try:
                    sound.play()
                except:
                    pass
            if(Score>40):
                account_sid = 'ACaca55b2aa6191b47199907ec57ba1246'
                auth_token = 'a9b0a69f7dd637316fb9f2e3853a57db'
                client = Client(account_sid, auth_token)

                message = client.messages.create(
                from_='+19403404222',
                body ='Alert!! The driver is down',
                to ='+916379365844'
                )
            break
                
        # if eyes are open
        elif prediction[0][1]>0.90:
            cv2.putText(frame,'open',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)      
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score = Score-1
            if (Score<0):
                Score=0
            
        
    cv2.imshow('frame',frame)
    if cv2.waitKey(33) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

1/1 [==============================] - 11s 11s/step
[[7.0734786e-11 1.0000000e+00]]
1/1 [==============================] - 0s 73ms/step
[[9.6459931e-05 9.9990356e-01]]
1/1 [==============================] - 0s 71ms/step
[[0.38470188 0.61529815]]
1/1 [==============================] - 0s 81ms/step
[[0.47981405 0.52018595]]
1/1 [==============================] - 0s 88ms/step
[[0.10043353 0.89956653]]
1/1 [==============================] - 0s 67ms/step
[[0.99850744 0.00149252]]
1/1 [==============================] - 0s 68ms/step
[[0.33728012 0.66271985]]
1/1 [==============================] - 0s 70ms/step
[[7.745431e-09 1.000000e+00]]
1/1 [==============================] - 0s 72ms/step
[[0.02270209 0.9772979 ]]
1/1 [==============================] - 0s 105ms/step
[[0.30112112 0.6988789 ]]
1/1 [==============================] - 0s 79ms/step
[[0.2698612  0.73013884]]
1/1 [==============================] - 0s 69ms/step
[[0.317394 0.682606]]
1/1 [==============================] - 0s 82ms/step

1/1 [==============================] - 0s 75ms/step
[[2.223095e-08 1.000000e+00]]
1/1 [==============================] - 0s 63ms/step
[[0.93735987 0.06264017]]
1/1 [==============================] - 0s 74ms/step
[[9.9944574e-01 5.5428891e-04]]
1/1 [==============================] - 0s 77ms/step
[[8.679145e-15 1.000000e+00]]
1/1 [==============================] - 0s 79ms/step
[[0.12709677 0.8729032 ]]
1/1 [==============================] - 0s 67ms/step
[[1.9971416e-19 1.0000000e+00]]
1/1 [==============================] - 0s 90ms/step
[[0.82050866 0.17949131]]
1/1 [==============================] - 0s 59ms/step
[[0.96988726 0.03011277]]
1/1 [==============================] - 0s 63ms/step
[[0.8458175  0.15418252]]
1/1 [==============================] - 0s 65ms/step
[[0.72266185 0.27733812]]
1/1 [==============================] - 0s 70ms/step
[[0.7031863 0.2968137]]
1/1 [==============================] - 0s 64ms/step
[[6.772517e-14 1.000000e+00]]
1/1 [==============================] - 0s 

[[0.99770457 0.00229549]]
1/1 [==============================] - 0s 70ms/step
[[0.12633432 0.87366563]]
1/1 [==============================] - 0s 96ms/step
[[6.2799395e-15 1.0000000e+00]]
1/1 [==============================] - 0s 112ms/step
[[0.13277005 0.86723   ]]
1/1 [==============================] - 0s 86ms/step
[[0.00233635 0.9976636 ]]
1/1 [==============================] - 0s 64ms/step
[[0.01532894 0.9846711 ]]
1/1 [==============================] - 0s 86ms/step
[[1.21678e-13 1.00000e+00]]
1/1 [==============================] - 0s 103ms/step
[[0.04037977 0.9596202 ]]
1/1 [==============================] - 0s 93ms/step
[[1.2439390e-04 9.9987555e-01]]
1/1 [==============================] - 0s 69ms/step
[[0.0178945 0.9821055]]
1/1 [==============================] - 0s 63ms/step
[[1.7896784e-06 9.9999821e-01]]
1/1 [==============================] - 0s 64ms/step
[[0.17198655 0.8280135 ]]
1/1 [==============================] - 0s 83ms/step
[[6.0257768e-09 1.0000000e+00]]
1/1 [=======